name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      doc_path: ${{ steps.set_path.outputs.doc_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          cd docs
          pip install -r requirements.txt
          cd ..

      - name: Build library
        run: |
          cd docs
          poetry install
          poetry build
          pip install dist/*.whl
          cd ..

      - name: Build documentation
        run: |
          cd docs
          make html
          cd ..

      - name: Set documentation path
        id: set_path
        run: echo "::set-output name=doc_path::docs/_build/html"

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ needs.build.outputs.doc_path }}