name: Documentation

on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      doc_path: ${{ steps.set_path.outputs.doc_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
            sudo apt update && sudo apt install -y \
              pkg-config libcairo-dev libpango1.0-dev wget fonts-roboto
            wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
            echo ${HOME}/.TinyTeX/bin/x86_64-linux >> $GITHUB_PATH

      - name: Install LaTeX dependencies
        run: |
          tlmgr update --self
          tlmgr install \
          babel-english ctex doublestroke dvisvgm frcursive fundus-calligra jknapltx \
          mathastext microtype physics preview ragged2e relsize rsfs setspace standalone \
          wasy wasysym

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build library
        run: |
          poetry install
          poetry build
          pip install $(ls dist/*.whl)

      - name: Install docs dependencies
        run: |
          cd docs
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Set documentation path
        id: set_path
        run: echo "doc_path=docs/_build/html" >> $GITHUB_OUTPUT

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html