name: Build and publish library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    outputs:
      version: ${{ steps.get_version.outputs.version }}
      is_prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build library
        run: |
          poetry build

      - name: Get version
        run: |
          VERSION=$(poetry version -s)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Check if version is pre-release
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" == *"alpha"* || "${{ steps.get_version.outputs.version }}" == *"beta"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: built_library
          path: ./dist

  create_github_release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Print version
        run: |
          echo "Version ${{ needs.build.outputs.version }}"


