name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build library
        run: |
          poetry build 

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: built_library
          path: ./dist

  run-tests:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-opengl libpango1.0-dev xvfb freeglut3-dev
          wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
          echo ${HOME}/.TinyTeX/bin/x86_64-linux >> $GITHUB_PATH

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install LaTeX dependencies
        run: |
          tlmgr update --self
          tlmgr install \
          babel-english ctex doublestroke dvisvgm frcursive fundus-calligra jknapltx \
          mathastext microtype physics preview ragged2e relsize rsfs setspace standalone \
          wasy wasysym
            

      - name: Download built library artifact
        uses: actions/download-artifact@v4
        with:
          name: built_library
          path: artifact

      - name: Install library
        run: |
          pip install artifact/*.tar.gz

      - name: Install dev dependencies
        run: |
          cd tests
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd tests
          pytest .
          
          
